NAME MARKERNAMES
ROWS
 N OBJ
 L C1
 L MARKER
COLUMNS
 X_MARKER_INTORG OBJ 1 C1 2
 MARKER OBJ 3 C1 4
 X MARKER 5
 START 'MARKER' 'INTORG'
 INTEGER_MARKER_INTEND OBJ 6 C1 7
 STOP "MARKER" "INTEND"
 CONT_MARKER_INTORG OBJ 8 C1 9
RHS
 RHS1 C1 20 MARKER 30
ENDATA
